management:
  endpoint:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  jackson:
    default-property-inclusion: non_null

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    urls:
      - name: student
        url: spec-student.yaml
