version: '3'
services:
  psql:
    image: postgres
    container_name: postgresql
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
      POSTGRES_PASSWORD: contingent-pass
      POSTGRES_USER: postgres
      POSTGRES_DB: contingent
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    image: contingent-app-spring
    container_name: app-spring
    ports:
      - "8080:8080"
    expose:
      - "8080"
    environment:
      SQL_URL: jdbc:postgresql://psql:5432/contingent
    depends_on:
      psql:
        condition: service_healthy

volumes:
  postgres_data:

