openapi: 3.0.4
info:
  title: Contingent log models
  description: Log models for logging services of Contingent
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
paths: {}

components:
  schemas:
    CommonLogModel:
      title: Общая модель лога
      description: Общая модель лога для всех микросервисов системы
      type: object
      properties:
        messageTime:
          type: string
        logId:
          type: string
        source:
          type: string
        student:
          $ref: '#/components/schemas/StudentLogModel'
        errors:
          type: array
          items:
            $ref: '#/components/schemas/ErrorLogModel'

    StudentLogModel:
      title: Модель лога для микросервиса Contingent
      type: object
      properties:
        requestId:
          type: string
        operation:
          type: string
          enum:
            - create
            - read
            - update
            - delete
            - search
        requestStud:
          $ref: '#/components/schemas/StudentLog'
        requestFilter:
          $ref: '#/components/schemas/StudentFilterLog'
        responseStud:
          $ref: '#/components/schemas/StudentLog'
        responseStuds:
          type: array
          items:
            $ref: '#/components/schemas/StudentLog'

    ErrorLogModel:
      title: Модель лога для ошибки
      type: object
      properties:
        message:
          type: string
        field:
          type: string
        code:
          type: string
        level:
          type: string

    StudentLog:
      title: Модель лога для студента
      type: object
      properties:
        id:
          type: integer
        fio:
          type: string
        sex:
          type: string
        semester:
          type: integer
        eduYear:
          type: integer
        facultyId:
          type: integer
        specialityId:
          type: integer
        groupNum:
          type: string

    StudentFilterLog:
      title: Модель лога фильтра
      properties:
        searchString:
          type: string

