### Добавить студента
POST http://localhost:8080/student/create
Authorization: Basic admin password
Content-Type: application/json

{
  "requestType": "create",
  "requestId": "1111",
  "debug": {
    "mode": "prod",
    "stub": "success"
  },
  "student": {
    "fio": "Иваанов Иван Иванович",
    "sex": "M",
    "semester": 3,
    "eduYear": 2023,
    "specialityId": 1,
    "facultyId": 2,
    "groupNum": "202-с"
  }
}

### Получить студента по id
POST http://localhost:8080/student/read
Authorization: Basic user password
Content-Type: application/json

{
  "requestType": "read",
  "requestId": "2222",
  "debug": {
    "mode": "prod",
    "stub": "success"
  },
  "student": {
    "id": 1
  }
}

### Обновить студента
POST http://localhost:8080/student/update
Authorization: Basic admin password
Content-Type: application/json

{
  "requestType": "update",
  "requestId": "3333",
  "debug": {
    "mode": "prod",
    "stub": "success"
  },
  "student": {
    "fio": "Петров Иван Иванович",
    "sex": "M",
    "semester": 3,
    "eduYear": 2023,
    "specialityId": 4,
    "facultyId": 2,
    "groupNum": "202-с",
    "id": 3,
    "lock": "?"
  }
}

### Удалить студента
POST http://localhost:8080/student/delete
Authorization: Basic admin password
Content-Type: application/json

{
  "requestType": "delete",
  "requestId": "4444",
  "debug": {
    "mode": "prod",
    "stub": "success"
  },
  "student": {
    "id": 2,
    "lock": "aee95903-68b8-4ef0-980a-4de5801c4e79"
  }
}

### Поиск студентов
POST http://localhost:8080/student/search
Authorization: Basic user password
Content-Type: application/json

{
  "requestType": "search",
  "requestId": "5555",
  "debug": {
    "mode": "prod",
    "stub": "success"
  },
  "studentFilter": {
    "searchString": ""
  }
}